;; Set up vim-plug
(local plug vim.fn.plug#)
(vim.call "plug#begin" "~/.config/nvim/plug")
(plug :pbrisbin/vim-syntax-shakespeare)
(plug :unisonweb/unison {:rtp :editor-support/vim :branch :trunk})
(plug :djoshea/vim-autoread)
(plug :alx741/yesod.vim)
(plug :ms-jpq/coq_nvim {:branch :coq})
(plug :5outh/yesod-routes.vim)
(plug :b3nj5m1n/kommentary)
(plug :bakpakin/fennel.vim)
(plug :danilo-augusto/vim-afterglow)
(plug :svermeulen/vimpeccable)
(vim.call "plug#end")
